FROM htm-images-registry-registry.cn-hangzhou.cr.aliyuncs.com/public/golang:1.16-base as builder
ARG GIT_USERNAME
ARG GIT_PASSWORD

# 将代码复制到容器中
COPY . /app

RUN export  GOPROXY=https://goproxy.cn
RUN export  GOPRIVATE=codeup.aliyun.com
RUN git config --global url.https://$GIT_USERNAME:$GIT_PASSWORD@codeup.aliyun.com.insteadOf https://codeup.aliyun.com
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags '-s -w' -o user-api service/user/api/user.go
WORKDIR /app

#打包
FROM htm-images-registry-registry.cn-hangzhou.cr.aliyuncs.com/public/centos:7.9-base

COPY user-api-dev.yaml /app/user-api-dev.yaml
COPY user-api-pro.yaml /app/user-api-pro.yaml
COPY user-api-uat.yaml /app/user-api-uat.yaml
COPY decision.yaml /app/decision.yaml

WORKDIR /app
COPY --from=builder /app/user-api .

CMD ["./user-api"]
